name: Build Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  build:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-22.04  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Load Env
        run: |
          python --version 
          python -m venv env 
          source env/bin/activate
          python install pip --upgrade
          python install -r requerements.txt

          
        
  
            


     
