
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos_intel:
    if: github.repository_owner == 'myridia'
    runs-on: macos-13
    steps:
      - name: get_repository
        run: |
          brew install python
   
      - name: checkout repo
        uses: actions/checkout@v4
 
      - name: list_targets
        run: |
          python --versoin
          python -m venv env 
          source env/bin/activate
          pip install pip --upgrade
          pyinstaller    main.py --onefile --path env/lib/site-packages --name=update_all_forks_mac 
    

      - name: Upload Macos Intel Binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/update_all_forks_mac'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true   
