name: Build Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  build:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-22.04  
    steps:
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: aschmelyun/cleaver:latest
     
