name: Build Linux/Windows Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build_linux_windows:
    if: github.repository_owner == 'myridia'
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: python --version 
        
    

        


        


 
     
