name: Build Linux/Windows Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build_linux_windows:
    if: github.repository_owner == 'myridia'
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        

      - name: build windows
        run: |
          python --version
          python -m venv env 
          ./env/Scripts/Activate.bat
          pip install pip --upgrade
          pip install -r requirements.txt 
          ./build.sh
          ls dist/
    
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/update_all_forks_windows.exe'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true   
        
    

        


        


 
     
